### ISSUE TITLE
Improve README documentation

### ISSUE THREAD

**Issue by dhimmel** [benchoufi/DocChain#1]
Greetings I'm a reviewer of the corresponding [F1000 article](https://f1000research.com/articles/6-66/v1 "Blockchain protocols in clinical trials: Transparency and traceability of consent"). Would it be possible to document this codebase in the README(s)?

For example, what do `agent` and `client` directories contain? How are the different parts of this repository executed?

**Comment by benchoufi** [comment]
Dear Daniel, 

Thank you for your interest, I am not the developer of the App, and I let my colleague @stephan83 complete what is below. Here's the required informations to get a global understanding of the code : 

* First, the client part

This consists in the website front-end. The framework in use is Angular. 

You’ll find the main services logic in the `services` folder such as file upload, email signing,…

You'll find the concrete implementations of these in the controllers - that you’ll find as usual in the `controller` folder

* Then, the agent part

This is the API that handles the bitcoin interaction, exposed through URL such as `https://docchain.stratumn.net/some/path/to/some/services` 
You’ll find these API calls in the Angular App through consistent calls to a `AgentFunctionURL` variable. Depending on the API call, this url is adjusted. 

I stay at disposal for any informations
 
Best,
Mehdi

**Comment by dhimmel** [comment]
Thanks @benchoufi for the explanation.

@stephan83, this information would be helpful in [`README.md`](https://github.com/benchoufi/DocChain/blob/7fb9eddad6114223299d253d278b8c73c940ad7f/README.md), which is currently just a one sentence description.

**Comment by benchoufi** [comment]
@dhimmel : after checking with @stephan83, we agreed that I would commit the change related to the `README.md` and this is done 

Best,
Mehdi

**Comment by dhimmel** [comment]
See https://github.com/benchoufi/DocChain/commit/ad0c71741257d8e9365230c6e57be69079ac966d
